workflows:
  ios-pwabuilder-build:
    name: PWABuilder iOS App Build
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      xcode: latest
      cocoapods: default
    working_directory: src
    scripts:
      - name: Install CocoaPods dependencies
        script: |
          pod install
      - name: Build iOS Application
        script: |
          WORKSPACE_FILE=$(ls -d *.xcworkspace | head -n 1)
          SCHEME_NAME=$(xcodebuild -list -workspace "$WORKSPACE_FILE" | grep -A 5 "Schemes:" | tail -n +2 | xargs | awk '{print $1}')
          xcodebuild -workspace "$WORKSPACE_FILE" -scheme "$SCHEME_NAME" -configuration Debug -sdk iphoneos CODE_SIGNING_ALLOWED=NO
      - name: Package App Bundle into IPA
        script: |
          mkdir -p Payload
          cp -r build/Build/Products/Debug-iphoneos/*.app Payload/
          zip -r habesha_app.ipa Payload
    artifacts:
      - "*.ipa"
