workflows:
  ios-pwabuilder-build:
    name: PWABuilder iOS App Build
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      xcode: latest
      cocoapods: default
    working_directory: src
    scripts:
      - name: Install CocoaPods dependencies
        script: |
          pod install
      - name: Build iOS IPA
        script: |
          xcodebuild -workspace *.xcworkspace -scheme "PWA" -configuration Release -archivePath build/PWA.xcarchive archive
          xcodebuild -exportArchive -archivePath build/PWA.xcarchive -exportPath build/outputs -exportOptionsPlist exportOptions.plist
    artifacts:
      - build/outputs/*.ipa
